module.exports = [
	// 'antd/lib/affix',
	'antd/lib/date-picker',
	// 'antd/lib/tooltip',
	// 'antd/lib/carousel',
	'antd/lib/tabs',
	// 'antd/lib/modal',
	'antd/lib/dropdown',
	// 'antd/lib/progress',
	// 'antd/lib/popover',
	'antd/lib/select',
	// 'antd/lib/breadcrumb',
	// 'antd/lib/popconfirm',
	'antd/lib/pagination',
	// 'antd/lib/steps',
	// 'antd/lib/input-number',
	// 'antd/lib/switch',
	// 'antd/lib/checkbox',
	'antd/lib/table',
	// 'antd/lib/tag',
	'antd/lib/collapse',
	// 'antd/lib/message',
	// 'antd/lib/slider',
	// 'antd/lib/queue-anim',
	// 'antd/lib/radio',
	// 'antd/lib/notification',:
	'antd/lib/alert',
	// 'antd/lib/validation',
	// 'antd/lib/tree',
	// 'antd/lib/upload',
	// 'antd/lib/badge',
	'antd/lib/menu',
	'antd/lib/timeline',
	'antd/lib/button',
	'antd/lib/icon',
	'antd/lib/row',
	'antd/lib/col',
	'antd/lib/spin',
	'antd/lib/form',
	'antd/lib/input',
	'antd/lib/calendar',
	'antd/lib/time-picker',
	// 'antd/lib/transfer'
] 
