var origin_antd_c = {
    Affix: require('antd_c/lib/affix'),
    DatePicker: require('antd_c/lib/date-picker'),
    Tooltip: require('antd_c/lib/tooltip'),
    Carousel: require('antd_c/lib/carousel'),
    Tabs: require('antd_c/lib/tabs'),
    Modal: require('antd_c/lib/modal'),
    Dropdown: require('antd_c/lib/dropdown'),
    Progress: require('antd_c/lib/progress'),
    Popover: require('antd_c/lib/popover'),
    Select: require('antd_c/lib/select'),
    Breadcrumb: require('antd_c/lib/breadcrumb'),
    Popconfirm: require('antd_c/lib/popconfirm'),
    Pagination: require('antd_c/lib/pagination'),
    Steps: require('antd_c/lib/steps'),
    InputNumber: require('antd_c/lib/input-number'),
    Switch: require('antd_c/lib/switch'),
    Checkbox: require('antd_c/lib/checkbox'),
    Table: require('antd_c/lib/table'),
    Tag: require('antd_c/lib/tag'),
    Collapse: require('antd_c/lib/collapse'),
    message: require('antd_c/lib/message'),
    Slider: require('antd_c/lib/slider'),
    QueueAnim: require('antd_c/lib/queue-anim'),
    Radio: require('antd_c/lib/radio'),
    notification: require('antd_c/lib/notification'),
    Alert: require('antd_c/lib/alert'),
    Validation: require('antd_c/lib/validation'),
    Tree: require('antd_c/lib/tree'),
    Upload: require('antd_c/lib/upload'),
    Badge: require('antd_c/lib/badge'),
    Menu: require('antd_c/lib/menu'),
    Timeline: require('antd_c/lib/timeline'),
    Button: require('antd_c/lib/button'),
    Icon: require('antd_c/lib/icon'),
    Row: require('antd_c/lib/row'),
    Col: require('antd_c/lib/col'),
    Spin: require('antd_c/lib/spin'),
    Form: require('antd_c/lib/form'),
    Input: require('antd_c/lib/input'),
    Calendar: require('antd_c/lib/calendar'),
    TimePicker: require('antd_c/lib/time-picker'),
    Transfer: require('antd_c/lib/transfer')
};

module.exports = origin_antd_c;
